###

GET http://localhost:3000/api/healthcheck

###

POST http://localhost:3000/api/register
Content-Type: application/json

{
  "teacher": {
    "name": "Teacher 1",
    "email": "teacher1@gmail.com"
  },
  "students": [
    {
      "name": "Student 1",
      "email": "student1@gmail.com"
    },
    {
      "name": "Student 2",
      "email": "student2@gmail.com"
    }
  ],
  "subject": {
    "subjectCode": "ENG",
    "name": "English"
  },
  "class": {
    "classCode": "P1-1",
    "name": "P1 Integrity"
  }
}

###

POST http://localhost:3000/api/reports/workload

###
